project:
  type: book
  output-dir: _book

book:
  title: "BM424 Clinical Microbiology Pandemic Preparedness Workshops"
  cover-image: sipbs_compbio_800.png
  favicon: icon_32.png
  page-navigation: false
    
  # Sets the page footer text/images
  # [B] FOOTER TEXT
  page-footer:
    center: |
      BM424 Workshops · 2024-25 · Dr Morgan Feeney
  author: "Dr Morgan Feeney"
  date: "28/02/2025"

  # Define chapters and sections here
  # [E] CHAPTERS AND SECTIONS
  chapters:
    - index.qmd
    - part: workshop3.qmd
      chapters: 
        - 3A.qmd
        - 3B.qmd
        - 3C.qmd
        - 3D.qmd
        - 3E.qmd
        - 3F.qmd
        - 3G.qmd
        - 3H.qmd
        - 3I.qmd
        





# Formatting and theme; may not need to be changed
format:
  html:
    theme: cosmo
    code-link: true
    fig-cap: true
    author-meta: "Leighton Pritchard"
    sidebar:
      style: "always"

# Freeze output before pushing modifications to the repository when publishing
# Should not need changing
execute:
  freeze: auto
