project:
  type: book
  output-dir: _book
  resources:
    - workshop3/dashboardA.qmd  # Keep it listed so it gets rendered

book:
  title: "BM424 Clinical Microbiology Pandemic Preparedness Workshops"
  cover-image: sipbs_compbio_800.png
  favicon: icon_32.png
  page-navigation: false
    
  # Sets the page footer text/images
  page-footer:
    center: |
      BM424 Workshops · 2024-25 · Dr Morgan Feeney
  author: "Dr Morgan Feeney"
  date: "28/02/2025"

  # Define chapters and contents here
  chapters:
    - index.qmd
    - workshop4.qmd
    - part: "Group A"
      chapters:
        - workshop4/4A.qmd
        - workshop4/dashboardA.qmd
    - part: "Group B"
      chapters: 
        - workshop4/4B.qmd
        - workshop4/dashboardB.qmd
    - part: "Group C"
      chapters: 
        - workshop4/4C.qmd
        - workshop4/dashboardC.qmd
    - part: "Group D"
      chapters: 
        - workshop4/4D.qmd
        - workshop4/dashboardD.qmd
    - part: "Group E"
      chapters: 
        - workshop4/4E.qmd
        - workshop4/dashboardE.qmd
    - part: "Group F"
      chapters: 
        - workshop4/4F.qmd
        - workshop4/dashboardF.qmd
    - part: "Group G"
      chapters: 
        - workshop4/4G.qmd
        - workshop4/dashboardG.qmd
    - part: "Group H"
      chapters: 
        - workshop4/4H.qmd
        - workshop4/dashboardH.qmd
    - part: "Group I - 1"
      chapters: 
        - workshop4/4I1.qmd
        - workshop4/dashboardI1.qmd
    - part: "Group I - 2"
      chapters: 
        - workshop4/4I2.qmd
        - workshop4/dashboardI2.qmd
        
    - workshop3.qmd
    - part: "Group A"
      chapters:
        - workshop3/3A.qmd
        - workshop3/dashboardA.qmd
        - workshop3/refA.qmd
    - part: "Group B"
      chapters: 
        - workshop3/3B.qmd
        - workshop3/dashboardB.qmd
        - workshop3/refB.qmd
    - part: "Group C"
      chapters: 
        - workshop3/3C.qmd
        - workshop3/dashboardC.qmd
        - workshop3/refC.qmd
    - part: "Group D"
      chapters: 
        - workshop3/3D.qmd
        - workshop3/dashboardD.qmd
        - workshop3/refD.qmd
    - part: "Group E"
      chapters: 
        - workshop3/3E.qmd
        - workshop3/dashboardE.qmd
        - workshop3/refE.qmd
    - part: "Group F"
      chapters: 
        - workshop3/3F.qmd
        - workshop3/dashboardF.qmd
        - workshop3/refF.qmd
    - part: "Group G"
      chapters: 
        - workshop3/3G.qmd
        - workshop3/dashboardG.qmd
        - workshop3/refG.qmd
    - part: "Group H"
      chapters: 
        - workshop3/3H.qmd
        - workshop3/dashboardH.qmd
        - workshop3/refH.qmd
    - part: "Group I"
      chapters: 
        - workshop3/3I.qmd
        - workshop3/dashboardI.qmd
        - workshop3/refI.qmd

# Formatting and theme; may not need to be changed
format:
  html:
    theme: cosmo
    code-link: true
    fig-cap: true
    author-meta: "Leighton Pritchard"
    sidebar:
      style: "always"

# Freeze output before pushing modifications to the repository when publishing
# Should not need changing
execute:
  freeze: auto
